on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      user:
        type: string
        required: true
      pat:
        type: string
        required: true
      version:
        type: string
        required: true

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    - name: nuget pack
      run: |
        cd .nuget
        nuget pack . -Version ${{ inputs.version }}
    - name: upload to github
      run: |
        nuget source Add -Name "github" -Source "https://nuget.pkg.github.com/tian-lt/index.json" -UserName "${{ inputs.user }}" -Password "${{ inputs.pat }}"
        nuget push "msft_proxy.${{ inputs.version }}.nupkg" -Source github
    