name: Proxy-Release

on:
  workflow_dispatch:
    inputs:
      version: 
        required: true
        default: '0.0.0'

jobs:
  draft-release:
    name: Draft release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    needs: report
    steps:
    - uses: actions/checkout@v4
    - name: pack and tag
      run: |
        ./tools/pack.sh

    - name: create release draft
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: proxy.tgz
        name: Proxy Release
        generate_release_notes: true
